-- Rune Tablet items missing from the English iteminfo (generated by
-- tools/rune_tablet/client_iteminfo.py from divine-pride.net dpRO English).
tbl_runetablet = {
	[105619] = {
		unidentifiedDisplayName = "Gaebolg Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 70 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Gaebolg Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 70 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105620] = {
		unidentifiedDisplayName = "Gaebolg Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Gaebolg Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105621] = {
		unidentifiedDisplayName = "Ice Seashore Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Ice Seashore Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105622] = {
		unidentifiedDisplayName = "Ice Seashore Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Ice Seashore Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105623] = {
		unidentifiedDisplayName = "Ice Seashore 2 Set Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Ice Seashore 2 Set Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105624] = {
		unidentifiedDisplayName = "Yosker Yorker Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Yosker Yorker Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105625] = {
		unidentifiedDisplayName = "Yosker Yorker Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 130 ea and Pure Diamond 4 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Yosker Yorker Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 130 ea and Pure Diamond 4 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105626] = {
		unidentifiedDisplayName = "Working Group Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 90 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Working Group Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 90 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105627] = {
		unidentifiedDisplayName = "Working Group Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Working Group Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105628] = {
		unidentifiedDisplayName = "Administrators Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Administrators Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105629] = {
		unidentifiedDisplayName = "Administrators Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 70 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Administrators Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 70 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105630] = {
		unidentifiedDisplayName = "Administrators 2 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Administrators 2 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105631] = {
		unidentifiedDisplayName = "Purification Activity Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 90 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Purification Activity Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 90 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105632] = {
		unidentifiedDisplayName = "Purification Activity Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 120 ea, Blacksmith's Blessing 1 ea and Pure Diamond 1 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Purification Activity Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 120 ea, Blacksmith's Blessing 1 ea and Pure Diamond 1 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105633] = {
		unidentifiedDisplayName = "Purification Activity 3 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Purification Activity 3 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105634] = {
		unidentifiedDisplayName = "Purification Activity 5 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Purification Activity 5 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105635] = {
		unidentifiedDisplayName = "Military Aid Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 90 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Military Aid Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 90 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105636] = {
		unidentifiedDisplayName = "Military Aid Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea, Episode 19-21 Card Album 1 ea and Blacksmith's Blessing 1 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Military Aid Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea, Episode 19-21 Card Album 1 ea and Blacksmith's Blessing 1 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105637] = {
		unidentifiedDisplayName = "Military Aid 2 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Military Aid 2 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105638] = {
		unidentifiedDisplayName = "Military Aid 4 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Military Aid 4 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105639] = {
		unidentifiedDisplayName = "Company Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 150 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Company Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 150 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105640] = {
		unidentifiedDisplayName = "Company Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 2 ea, Imperfect Rune 450 ea, Golden Diamond 5 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Company Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 2 ea, Imperfect Rune 450 ea, Golden Diamond 5 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105641] = {
		unidentifiedDisplayName = "Company 3 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea, Episode 19-21 Card Album 1 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Company 3 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea, Episode 19-21 Card Album 1 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105642] = {
		unidentifiedDisplayName = "Company 5 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Blacksmith's Blessing 1 ea and Imperfect Rune 150 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Company 5 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Blacksmith's Blessing 1 ea and Imperfect Rune 150 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105643] = {
		unidentifiedDisplayName = "Frozen Horn Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 180 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Frozen Horn Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 180 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105644] = {
		unidentifiedDisplayName = "Frozen Horn Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 2 ea, Imperfect Rune 450 ea, Golden Diamond 5 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Frozen Horn Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 2 ea, Imperfect Rune 450 ea, Golden Diamond 5 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105645] = {
		unidentifiedDisplayName = "Frozen Horn 3 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea, Episode 19-21 Card Album 1 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Frozen Horn 3 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea, Episode 19-21 Card Album 1 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105646] = {
		unidentifiedDisplayName = "Frozen Horn 5 Sets Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Blacksmith's Blessing 1 ea, Imperfect Rune 150 ea, Pure Diamond 3 ea and Episode 19-21 Card Album 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Frozen Horn 5 Sets Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Blacksmith's Blessing 1 ea, Imperfect Rune 150 ea, Pure Diamond 3 ea and Episode 19-21 Card Album 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105647] = {
		unidentifiedDisplayName = "Encroachment Activation Reward",
		unidentifiedResourceName = "Rt_Ep21_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 180 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Encroachment Activation Reward",
		identifiedResourceName = "Rt_Ep21_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 180 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[105648] = {
		unidentifiedDisplayName = "Encroachment Completion Reward",
		unidentifiedResourceName = "Rt_Ep21_C",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 2 ea, Imperfect Rune 500 ea, Golden Diamond 5 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Encroachment Completion Reward",
		identifiedResourceName = "Rt_Ep21_C",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 2 ea, Imperfect Rune 500 ea, Golden Diamond 5 ea and Episode 19-21 Card Album 1 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106408] = {
		unidentifiedDisplayName = "Fire Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 200 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Fire Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 200 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106409] = {
		unidentifiedDisplayName = "Fire Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 3 ea, Imperfect Rune 500 ea and Golden Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Fire Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 3 ea, Imperfect Rune 500 ea and Golden Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106410] = {
		unidentifiedDisplayName = "Predator Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 200 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Predator Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 200 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106411] = {
		unidentifiedDisplayName = "Predator Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 3 ea, Imperfect Rune 500 ea and Golden Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Predator Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 3 ea, Imperfect Rune 500 ea and Golden Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106412] = {
		unidentifiedDisplayName = "Uncanny Fruit Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Uncanny Fruit Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106413] = {
		unidentifiedDisplayName = "Uncanny Fruit Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Uncanny Fruit Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106414] = {
		unidentifiedDisplayName = "Uncanny Fruit 2 Sets Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Uncanny Fruit 2 Sets Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106415] = {
		unidentifiedDisplayName = "Junkyard Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Junkyard Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106416] = {
		unidentifiedDisplayName = "Junkyard Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Junkyard Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106417] = {
		unidentifiedDisplayName = "Noise Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Noise Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106418] = {
		unidentifiedDisplayName = "Noise Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Noise Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106419] = {
		unidentifiedDisplayName = "Noise 2 Sets Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Noise 2 Sets Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 80 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106420] = {
		unidentifiedDisplayName = "Creepy Flower Garden Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Creepy Flower Garden Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106421] = {
		unidentifiedDisplayName = "Creepy Flower Garden Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Creepy Flower Garden Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106422] = {
		unidentifiedDisplayName = "Toxic Sidekick Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Toxic Sidekick Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106423] = {
		unidentifiedDisplayName = "Toxic Sidekick Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Toxic Sidekick Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 3 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106424] = {
		unidentifiedDisplayName = "Toxic Sidekick 3 Sets Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Toxic Sidekick 3 Sets Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106425] = {
		unidentifiedDisplayName = "Small and Warm Activation Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Small and Warm Activation Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Perfect Rune 1 ea and Imperfect Rune 100 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106426] = {
		unidentifiedDisplayName = "Small and Warm Completion Reward",
		unidentifiedResourceName = "Rt_Ch01_C",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Small and Warm Completion Reward",
		identifiedResourceName = "Rt_Ch01_C",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 150 ea and Pure Diamond 2 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[106427] = {
		unidentifiedDisplayName = "Small and Warm 3 Sets Reward",
		unidentifiedResourceName = "Rt_Ch01_A",
		unidentifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 1 ea.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Small and Warm 3 Sets Reward",
		identifiedResourceName = "Rt_Ch01_A",
		identifiedDescriptionName = {
			"A reward box containing Imperfect Rune 100 ea and Pure Diamond 1 ea.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002473] = {
		unidentifiedDisplayName = "Printed Gaebolg Armor",
		unidentifiedResourceName = "R_Gaebolg_Armor",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Armor",
		identifiedResourceName = "R_Gaebolg_Armor",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002474] = {
		unidentifiedDisplayName = "Printed Gaebolg Robe",
		unidentifiedResourceName = "R_Gaebolg_Robe",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Robe",
		identifiedResourceName = "R_Gaebolg_Robe",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002475] = {
		unidentifiedDisplayName = "Printed Gaebolg Manteau",
		unidentifiedResourceName = "R_Gaebolg_Manteau",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Manteau",
		identifiedResourceName = "R_Gaebolg_Manteau",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002476] = {
		unidentifiedDisplayName = "Printed Gaebolg Muffler",
		unidentifiedResourceName = "R_Gaebolg_Muffler",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Muffler",
		identifiedResourceName = "R_Gaebolg_Muffler",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002477] = {
		unidentifiedDisplayName = "Printed Gaebolg Boots",
		unidentifiedResourceName = "R_Gaebolg_Boots",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Boots",
		identifiedResourceName = "R_Gaebolg_Boots",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002478] = {
		unidentifiedDisplayName = "Printed Gaebolg Shoes",
		unidentifiedResourceName = "R_Gaebolg_Shoes",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Shoes",
		identifiedResourceName = "R_Gaebolg_Shoes",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002479] = {
		unidentifiedDisplayName = "Printed Gaebolg Ring",
		unidentifiedResourceName = "R_Gaebolg_Ring",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Ring",
		identifiedResourceName = "R_Gaebolg_Ring",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002480] = {
		unidentifiedDisplayName = "Printed Gaebolg Glove",
		unidentifiedResourceName = "R_Gaebolg_Glove",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Glove",
		identifiedResourceName = "R_Gaebolg_Glove",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002481] = {
		unidentifiedDisplayName = "Printed Gaebolg Earring",
		unidentifiedResourceName = "R_Gaebolg_Earring",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Earring",
		identifiedResourceName = "R_Gaebolg_Earring",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[1002482] = {
		unidentifiedDisplayName = "Printed Gaebolg Necklace",
		unidentifiedResourceName = "R_Gaebolg_Necklace",
		unidentifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		identifiedDisplayName = "Printed Gaebolg Necklace",
		identifiedResourceName = "R_Gaebolg_Necklace",
		identifiedDescriptionName = {
			"An item that was printed with its power sealed.",
			"It can no longer be used, but the power of the item is preserved.",
			"Weight: ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		Server = "kRO"
	},
	[27266] = {
		unidentifiedDisplayName = "Hunter Fly Card",
		unidentifiedResourceName = "\192\204\184\167\190\248\180\194\196\171\181\229",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Hunter Fly Card",
		identifiedResourceName = "\192\204\184\167\190\248\180\194\196\171\181\229",
		identifiedDescriptionName = {
			"Physical attacks have a 5% chance to restore 100 HP every second for 5 seconds.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Weapon",
			"^0000CCWeight:^000000 1"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
	[300483] = {
		unidentifiedDisplayName = "Mid-grade Rune Card",
		unidentifiedResourceName = "\192\204\184\167\190\248\180\194\196\171\181\229",
		unidentifiedDescriptionName = { "" },
		identifiedDisplayName = "Mid-grade Rune Card",
		identifiedResourceName = "\192\204\184\167\190\248\180\194\196\171\181\229",
		identifiedDescriptionName = {
			"A blank card with no abilities.",
			"It looks like it can be dismantled with a Rune Tablet.",
			"_______________________",
			"^0000CCType:^000000 Card",
			"^0000CCCompound on:^000000 Headgear",
			"^0000CCWeight:^000000 0"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		EffectID = 1186
	},
}
